return {
  {
    {
      "monaqa/dial.nvim",
      config = function()
        local augend = require("dial.augend")
        require("dial.config").augends:register_group({
          default = {
            augend.integer.alias.decimal,
            augend.integer.alias.hex,
            augend.integer.alias.octal,
            augend.integer.alias.binary,
            augend.date.alias["%Y/%m/%d"],
            augend.semver.alias.semver,
            augend.constant.alias.alpha,
            augend.constant.alias.Alpha,
            augend.constant.alias.de_weekday,
            augend.constant.alias.de_weekday_full,
            augend.constant.alias.en_weekday,
            augend.constant.alias.en_weekday_full,
            augend.constant.alias.bool, -- true/false
            augend.constant.new({ elements = { "&&", "||" }, word = false }),
            augend.constant.new({ elements = { "and", "or" } }),
            augend.constant.new({ elements = { "public", "protected", "private" } }),
            augend.constant.new({ elements = { "let", "const", "var" } }),
            augend.constant.new({ elements = { "INFO", "WARN", "ERROR", "DEBUG" } }),
            augend.constant.new({
              elements = {
                "α",
                "β",
                "γ",
                "δ",
                "ε",
                "ζ",
                "η",
                "θ",
                "ι",
                "κ",
                "λ",
                "μ",
                "ν",
                "ξ",
                "ο",
                "π",
                "ρ",
                "σ",
                "τ",
                "υ",
                "φ",
                "χ",
                "ψ",
                "ω",
              },
            }),
            augend.constant.new({
              elements = {
                "Α",
                "Β",
                "Γ",
                "Δ",
                "Ε",
                "Ζ",
                "Η",
                "Θ",
                "Ι",
                "Κ",
                "Λ",
                "Μ",
                "Ν",
                "Ξ",
                "Ο",
                "Π",
                "Ρ",
                "Σ",
                "Τ",
                "Υ",
                "Φ",
                "Χ",
                "Ψ",
                "Ω",
              },
            }),
          },
        })
        vim.keymap.set({ "n", "v" }, "<C-a>", require("dial.map").inc_normal())
        vim.keymap.set({ "n", "v" }, "<C-x>", require("dial.map").dec_normal())
      end,
    },
  },
}
